// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task2.DataAccess;

#nullable disable

namespace Task2.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220921091336_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Task2.DataAccess.DomainModels.ArticleMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aabebeaa-d82d-4bb1-b8cb-19f580a25115"),
                            Name = "Magni voluptas fuga",
                            PublishDate = new DateTime(2020, 6, 16, 15, 7, 52, 545, DateTimeKind.Local).AddTicks(1598),
                            Source = "http://everette.net"
                        },
                        new
                        {
                            Id = new Guid("fc52fe88-2837-43cd-be40-6d4c0b21db01"),
                            Name = "Placeat repudiandae quia",
                            PublishDate = new DateTime(2022, 3, 10, 15, 30, 0, 625, DateTimeKind.Local).AddTicks(4646),
                            Source = "https://jaleel.name"
                        },
                        new
                        {
                            Id = new Guid("2bba1d01-c17b-4de6-9c1c-bd092b4d0127"),
                            Name = "Debitis fugiat fugit",
                            PublishDate = new DateTime(2020, 1, 13, 22, 10, 59, 918, DateTimeKind.Local).AddTicks(2654),
                            Source = "http://vicente.info"
                        },
                        new
                        {
                            Id = new Guid("f683da48-dad8-43db-a067-8a2a5bacd046"),
                            Name = "Debitis accusamus facilis",
                            PublishDate = new DateTime(2020, 7, 23, 5, 8, 50, 42, DateTimeKind.Local).AddTicks(4328),
                            Source = "http://sanford.info"
                        },
                        new
                        {
                            Id = new Guid("3a7f0449-81ac-421c-bf24-c007efc0f2ca"),
                            Name = "Blanditiis quia consectetur",
                            PublishDate = new DateTime(2020, 4, 25, 12, 20, 39, 165, DateTimeKind.Local).AddTicks(6732),
                            Source = "http://jackson.net"
                        },
                        new
                        {
                            Id = new Guid("2b3b123c-7228-4eb3-b138-8eda3638fbe0"),
                            Name = "Expedita est doloribus",
                            PublishDate = new DateTime(2021, 11, 15, 22, 35, 37, 879, DateTimeKind.Local).AddTicks(8798),
                            Source = "http://kaleigh.name"
                        },
                        new
                        {
                            Id = new Guid("544719ec-ad7d-4af7-8a16-161b13b75297"),
                            Name = "Ducimus consectetur ut",
                            PublishDate = new DateTime(2021, 7, 9, 5, 58, 33, 214, DateTimeKind.Local).AddTicks(4641),
                            Source = "http://marco.info"
                        },
                        new
                        {
                            Id = new Guid("6a9e9433-3c92-464b-a035-db95754b42e0"),
                            Name = "Sunt iste eos",
                            PublishDate = new DateTime(2020, 3, 9, 21, 5, 29, 327, DateTimeKind.Local).AddTicks(1390),
                            Source = "https://jeffrey.name"
                        },
                        new
                        {
                            Id = new Guid("2adc29ea-db91-438f-baf5-e4f574ae50dc"),
                            Name = "Officia ullam voluptas",
                            PublishDate = new DateTime(2021, 7, 27, 22, 0, 4, 364, DateTimeKind.Local).AddTicks(7689),
                            Source = "http://arch.biz"
                        },
                        new
                        {
                            Id = new Guid("5aa5544e-e1e3-4733-b3c7-3b841dfea2d7"),
                            Name = "Temporibus reprehenderit et",
                            PublishDate = new DateTime(2020, 7, 4, 17, 18, 17, 6, DateTimeKind.Local).AddTicks(163),
                            Source = "https://judson.info"
                        },
                        new
                        {
                            Id = new Guid("acbbcf1f-b283-463f-a7f2-217bf4654fef"),
                            Name = "Qui laudantium qui",
                            PublishDate = new DateTime(2021, 6, 11, 23, 59, 38, 855, DateTimeKind.Local).AddTicks(7162),
                            Source = "https://ollie.net"
                        },
                        new
                        {
                            Id = new Guid("d957c55d-9727-470b-8c89-e1a67a8da216"),
                            Name = "Deleniti suscipit totam",
                            PublishDate = new DateTime(2020, 7, 11, 21, 28, 48, 845, DateTimeKind.Local).AddTicks(4527),
                            Source = "https://murray.info"
                        },
                        new
                        {
                            Id = new Guid("aa40a4b1-c25e-402b-a6e4-d1bf5cc60d87"),
                            Name = "Veniam nihil voluptas",
                            PublishDate = new DateTime(2022, 2, 18, 17, 31, 54, 87, DateTimeKind.Local).AddTicks(1273),
                            Source = "https://lessie.name"
                        },
                        new
                        {
                            Id = new Guid("c5de7bdc-4a31-4a88-8a93-1e6ac26c174a"),
                            Name = "Est quia qui",
                            PublishDate = new DateTime(2020, 3, 31, 13, 26, 13, 510, DateTimeKind.Local).AddTicks(165),
                            Source = "https://everardo.biz"
                        },
                        new
                        {
                            Id = new Guid("21bfd0a6-313f-4360-9c5c-92da9ff943f5"),
                            Name = "Ut optio ad",
                            PublishDate = new DateTime(2021, 6, 4, 15, 38, 3, 358, DateTimeKind.Local).AddTicks(4910),
                            Source = "http://quinn.net"
                        },
                        new
                        {
                            Id = new Guid("faf855dd-817e-470d-8abd-dcef54273191"),
                            Name = "Aut qui cumque",
                            PublishDate = new DateTime(2022, 7, 10, 19, 42, 58, 317, DateTimeKind.Local).AddTicks(97),
                            Source = "http://letitia.info"
                        },
                        new
                        {
                            Id = new Guid("a974f859-959d-4506-a78a-3bd8df91ed3e"),
                            Name = "Quo facere et",
                            PublishDate = new DateTime(2019, 11, 4, 12, 34, 15, 717, DateTimeKind.Local).AddTicks(3732),
                            Source = "http://cary.biz"
                        },
                        new
                        {
                            Id = new Guid("5da2695c-3484-481f-addc-5468f0e36d4d"),
                            Name = "Autem hic ducimus",
                            PublishDate = new DateTime(2021, 11, 24, 20, 24, 43, 25, DateTimeKind.Local).AddTicks(2389),
                            Source = "http://hettie.org"
                        },
                        new
                        {
                            Id = new Guid("bf118d7d-4f95-4420-9017-9492e38be94c"),
                            Name = "Consequatur autem vero",
                            PublishDate = new DateTime(2021, 8, 10, 18, 38, 17, 214, DateTimeKind.Local).AddTicks(5703),
                            Source = "http://birdie.info"
                        },
                        new
                        {
                            Id = new Guid("3ecfc6c3-f43f-4446-838f-5634c93882dc"),
                            Name = "Aut ea sunt",
                            PublishDate = new DateTime(2022, 5, 26, 15, 36, 25, 29, DateTimeKind.Local).AddTicks(9530),
                            Source = "http://aletha.info"
                        },
                        new
                        {
                            Id = new Guid("93e5f372-3554-4ba6-b8d5-89d184e2b207"),
                            Name = "Laudantium aspernatur culpa",
                            PublishDate = new DateTime(2020, 12, 6, 7, 6, 50, 331, DateTimeKind.Local).AddTicks(6910),
                            Source = "http://mateo.net"
                        },
                        new
                        {
                            Id = new Guid("5d99013a-8442-4ce5-ac7b-cc83054b35ca"),
                            Name = "Est consequuntur atque",
                            PublishDate = new DateTime(2022, 6, 24, 1, 11, 57, 139, DateTimeKind.Local).AddTicks(7893),
                            Source = "https://maynard.biz"
                        },
                        new
                        {
                            Id = new Guid("83e7d345-b590-4ee7-80cd-7f29bf032f99"),
                            Name = "Minus vel ut",
                            PublishDate = new DateTime(2019, 12, 13, 19, 19, 25, 22, DateTimeKind.Local).AddTicks(3134),
                            Source = "https://marc.net"
                        },
                        new
                        {
                            Id = new Guid("46408047-5ecd-4a5d-843e-971b2cdf1815"),
                            Name = "Necessitatibus fugiat sed",
                            PublishDate = new DateTime(2022, 2, 26, 1, 42, 24, 251, DateTimeKind.Local).AddTicks(4221),
                            Source = "https://winona.org"
                        },
                        new
                        {
                            Id = new Guid("6efb0fc3-ffd4-4178-8a16-3ebd49d2e296"),
                            Name = "Numquam facilis et",
                            PublishDate = new DateTime(2020, 9, 17, 14, 21, 39, 175, DateTimeKind.Local).AddTicks(3895),
                            Source = "http://delores.org"
                        },
                        new
                        {
                            Id = new Guid("78cbf6d1-ffe1-4937-996c-22967de028d8"),
                            Name = "Odit ratione quia",
                            PublishDate = new DateTime(2020, 3, 12, 18, 27, 57, 87, DateTimeKind.Local).AddTicks(8161),
                            Source = "https://savion.net"
                        },
                        new
                        {
                            Id = new Guid("fadfe8b1-be8f-4cbe-bc8f-0968f325e2fc"),
                            Name = "Velit itaque iure",
                            PublishDate = new DateTime(2020, 1, 27, 9, 13, 39, 3, DateTimeKind.Local).AddTicks(4940),
                            Source = "http://katlyn.biz"
                        },
                        new
                        {
                            Id = new Guid("8f4288d6-cd96-4ee0-b339-4e5a8877afaf"),
                            Name = "Quo qui reprehenderit",
                            PublishDate = new DateTime(2021, 12, 26, 19, 16, 52, 914, DateTimeKind.Local).AddTicks(8019),
                            Source = "https://grady.biz"
                        },
                        new
                        {
                            Id = new Guid("91dee07e-0e1c-4d41-bf54-408bb9281bd8"),
                            Name = "Autem aut repellendus",
                            PublishDate = new DateTime(2022, 4, 9, 15, 31, 55, 405, DateTimeKind.Local).AddTicks(1522),
                            Source = "http://amira.info"
                        },
                        new
                        {
                            Id = new Guid("61324abb-643a-40fd-95d0-72af8252459e"),
                            Name = "Cupiditate amet expedita",
                            PublishDate = new DateTime(2021, 7, 30, 6, 54, 20, 41, DateTimeKind.Local).AddTicks(1260),
                            Source = "http://elisha.name"
                        },
                        new
                        {
                            Id = new Guid("7ead2412-a565-4bad-9558-f8fff1fb318d"),
                            Name = "Esse fuga voluptatem",
                            PublishDate = new DateTime(2021, 2, 21, 23, 33, 0, 144, DateTimeKind.Local).AddTicks(441),
                            Source = "https://devin.org"
                        },
                        new
                        {
                            Id = new Guid("b7946e00-1127-43a4-acd5-c13bded163ed"),
                            Name = "Natus nam corporis",
                            PublishDate = new DateTime(2020, 1, 12, 12, 33, 14, 978, DateTimeKind.Local).AddTicks(5396),
                            Source = "https://nelda.info"
                        },
                        new
                        {
                            Id = new Guid("8da90ec4-aa5c-44e3-aca7-5b95957b2d12"),
                            Name = "Et ut ducimus",
                            PublishDate = new DateTime(2020, 4, 24, 9, 28, 37, 775, DateTimeKind.Local).AddTicks(6678),
                            Source = "http://zula.name"
                        },
                        new
                        {
                            Id = new Guid("de6f8aba-eb87-4ae9-ad16-6434362d31a8"),
                            Name = "Laudantium corporis quisquam",
                            PublishDate = new DateTime(2020, 7, 17, 0, 52, 19, 830, DateTimeKind.Local).AddTicks(636),
                            Source = "https://prudence.com"
                        },
                        new
                        {
                            Id = new Guid("6efc4f92-3671-4993-985c-63d39b9c0e02"),
                            Name = "Et accusamus aperiam",
                            PublishDate = new DateTime(2021, 3, 13, 0, 51, 43, 28, DateTimeKind.Local).AddTicks(5293),
                            Source = "http://graciela.info"
                        },
                        new
                        {
                            Id = new Guid("94e7ade9-95cb-4070-969b-eba400c5f4e7"),
                            Name = "Autem incidunt autem",
                            PublishDate = new DateTime(2020, 1, 30, 20, 10, 53, 369, DateTimeKind.Local).AddTicks(3505),
                            Source = "https://antonette.com"
                        },
                        new
                        {
                            Id = new Guid("d09fc2e6-4393-4fc4-8639-011f7760d191"),
                            Name = "Ut ut iure",
                            PublishDate = new DateTime(2020, 9, 14, 11, 35, 39, 991, DateTimeKind.Local).AddTicks(4909),
                            Source = "https://alexander.biz"
                        },
                        new
                        {
                            Id = new Guid("03cdd312-c01e-480c-983b-582ef977f778"),
                            Name = "Voluptate adipisci a",
                            PublishDate = new DateTime(2022, 3, 12, 20, 45, 27, 70, DateTimeKind.Local).AddTicks(2842),
                            Source = "http://eusebio.name"
                        },
                        new
                        {
                            Id = new Guid("1ade486f-fbe2-485e-9a9f-e9aef62b5db3"),
                            Name = "Error quae quibusdam",
                            PublishDate = new DateTime(2020, 5, 15, 3, 48, 27, 755, DateTimeKind.Local).AddTicks(4195),
                            Source = "http://raymond.com"
                        },
                        new
                        {
                            Id = new Guid("f8c94833-c258-4d17-b2b3-e8bd59d18714"),
                            Name = "Minima laudantium eos",
                            PublishDate = new DateTime(2022, 6, 4, 17, 27, 46, 693, DateTimeKind.Local).AddTicks(9118),
                            Source = "https://vernie.org"
                        },
                        new
                        {
                            Id = new Guid("3724146a-f9c4-40f8-b566-ef5b7461688d"),
                            Name = "Assumenda explicabo ut",
                            PublishDate = new DateTime(2021, 5, 16, 20, 21, 15, 241, DateTimeKind.Local).AddTicks(9427),
                            Source = "https://harvey.net"
                        },
                        new
                        {
                            Id = new Guid("b37af3da-5376-490e-b00f-2ce69df7834c"),
                            Name = "Beatae non amet",
                            PublishDate = new DateTime(2021, 5, 23, 8, 22, 33, 515, DateTimeKind.Local).AddTicks(8374),
                            Source = "http://marques.name"
                        },
                        new
                        {
                            Id = new Guid("6f65f72c-4ae7-477b-a803-46cae13b43a1"),
                            Name = "Vero voluptas sunt",
                            PublishDate = new DateTime(2021, 12, 11, 12, 8, 37, 612, DateTimeKind.Local).AddTicks(8454),
                            Source = "https://chanel.org"
                        },
                        new
                        {
                            Id = new Guid("00e2d9ca-5286-4919-983a-d856161930e9"),
                            Name = "Vitae quia deserunt",
                            PublishDate = new DateTime(2022, 5, 16, 1, 38, 37, 806, DateTimeKind.Local).AddTicks(1773),
                            Source = "http://tara.com"
                        },
                        new
                        {
                            Id = new Guid("92bfd4d0-4ec6-43fe-8341-f36c4306901f"),
                            Name = "Dolorem aliquam odio",
                            PublishDate = new DateTime(2020, 7, 6, 5, 6, 15, 63, DateTimeKind.Local).AddTicks(9243),
                            Source = "http://earline.biz"
                        },
                        new
                        {
                            Id = new Guid("8c27e230-be08-4235-af1b-23520f23d5b8"),
                            Name = "Corporis incidunt dolorem",
                            PublishDate = new DateTime(2019, 11, 29, 7, 48, 16, 926, DateTimeKind.Local).AddTicks(1281),
                            Source = "http://vesta.net"
                        },
                        new
                        {
                            Id = new Guid("99edc7a6-2f65-4893-abd9-5ee1a2e070ae"),
                            Name = "Deserunt nostrum ipsum",
                            PublishDate = new DateTime(2020, 5, 3, 23, 23, 17, 163, DateTimeKind.Local).AddTicks(1464),
                            Source = "http://arvel.org"
                        },
                        new
                        {
                            Id = new Guid("65a05f20-cfd2-47ff-b02d-857806bc11ac"),
                            Name = "Perspiciatis deserunt expedita",
                            PublishDate = new DateTime(2022, 1, 7, 23, 42, 30, 373, DateTimeKind.Local).AddTicks(6219),
                            Source = "http://elvie.biz"
                        },
                        new
                        {
                            Id = new Guid("0ee6ff87-00a9-40bd-96e1-ce640692fbf0"),
                            Name = "Delectus odio iste",
                            PublishDate = new DateTime(2021, 9, 16, 17, 48, 54, 961, DateTimeKind.Local).AddTicks(8867),
                            Source = "http://nasir.com"
                        },
                        new
                        {
                            Id = new Guid("2b32cf24-a82c-4515-a49c-5a099fe884c1"),
                            Name = "Nisi suscipit veritatis",
                            PublishDate = new DateTime(2019, 10, 3, 21, 55, 50, 160, DateTimeKind.Local).AddTicks(7245),
                            Source = "http://cale.info"
                        },
                        new
                        {
                            Id = new Guid("d8f2bbe0-1c0d-457c-9a81-cf3b07002c71"),
                            Name = "Omnis qui tempora",
                            PublishDate = new DateTime(2020, 12, 15, 20, 29, 15, 374, DateTimeKind.Local).AddTicks(2495),
                            Source = "https://wilton.net"
                        },
                        new
                        {
                            Id = new Guid("b953fa2d-ce7c-4226-be13-db5c76ee7417"),
                            Name = "Natus consequuntur rerum",
                            PublishDate = new DateTime(2021, 4, 4, 4, 38, 59, 99, DateTimeKind.Local).AddTicks(4813),
                            Source = "https://leland.net"
                        },
                        new
                        {
                            Id = new Guid("e220ef41-807c-4774-82fa-e42e0fb04707"),
                            Name = "Hic facilis tempora",
                            PublishDate = new DateTime(2020, 7, 24, 17, 18, 46, 336, DateTimeKind.Local).AddTicks(3529),
                            Source = "https://hildegard.info"
                        },
                        new
                        {
                            Id = new Guid("03813089-6293-4e38-998d-536106fe5fba"),
                            Name = "Neque eaque enim",
                            PublishDate = new DateTime(2022, 5, 19, 11, 21, 35, 626, DateTimeKind.Local).AddTicks(5847),
                            Source = "http://nathan.name"
                        },
                        new
                        {
                            Id = new Guid("4278f613-5ed2-46be-bda8-8a046d91c069"),
                            Name = "Maiores cum aut",
                            PublishDate = new DateTime(2022, 3, 16, 9, 58, 54, 106, DateTimeKind.Local).AddTicks(7496),
                            Source = "https://hershel.com"
                        },
                        new
                        {
                            Id = new Guid("6d43f927-a537-44a2-8862-05fc47d1a227"),
                            Name = "Eveniet similique molestiae",
                            PublishDate = new DateTime(2019, 12, 19, 18, 31, 30, 294, DateTimeKind.Local).AddTicks(7226),
                            Source = "http://hubert.info"
                        },
                        new
                        {
                            Id = new Guid("55fab735-0829-47c4-a507-b4e0aafccf75"),
                            Name = "A ut dolore",
                            PublishDate = new DateTime(2022, 9, 16, 22, 44, 4, 425, DateTimeKind.Local).AddTicks(2790),
                            Source = "https://randy.name"
                        },
                        new
                        {
                            Id = new Guid("96cff470-5b4c-4582-a693-bff10aa2f425"),
                            Name = "Nemo vitae illum",
                            PublishDate = new DateTime(2021, 3, 10, 8, 23, 55, 924, DateTimeKind.Local).AddTicks(9014),
                            Source = "https://charity.info"
                        },
                        new
                        {
                            Id = new Guid("09718fc2-f257-451a-854e-b69db8f083e6"),
                            Name = "Dignissimos reprehenderit culpa",
                            PublishDate = new DateTime(2021, 4, 17, 0, 11, 38, 590, DateTimeKind.Local).AddTicks(121),
                            Source = "https://godfrey.com"
                        },
                        new
                        {
                            Id = new Guid("4cb893c5-e7a2-4ea8-a08d-ef4ffa4f97ef"),
                            Name = "Culpa debitis dolorem",
                            PublishDate = new DateTime(2022, 7, 23, 5, 48, 22, 681, DateTimeKind.Local).AddTicks(4365),
                            Source = "https://hailey.name"
                        },
                        new
                        {
                            Id = new Guid("383a7005-a906-4904-bab6-23b44732eb70"),
                            Name = "Rem iste et",
                            PublishDate = new DateTime(2020, 6, 29, 14, 59, 55, 28, DateTimeKind.Local).AddTicks(6242),
                            Source = "https://alyson.com"
                        },
                        new
                        {
                            Id = new Guid("c096ed02-cd0c-42db-a4d2-f56320562746"),
                            Name = "Minima odio qui",
                            PublishDate = new DateTime(2021, 4, 6, 12, 53, 9, 689, DateTimeKind.Local).AddTicks(9591),
                            Source = "https://hershel.info"
                        },
                        new
                        {
                            Id = new Guid("714e7535-a4ea-4425-9f5a-4b3219cfb4d7"),
                            Name = "Officiis dolore distinctio",
                            PublishDate = new DateTime(2022, 1, 18, 6, 1, 45, 547, DateTimeKind.Local).AddTicks(7806),
                            Source = "https://emery.biz"
                        },
                        new
                        {
                            Id = new Guid("38897850-1bd7-469d-b86f-972057ca3bf1"),
                            Name = "Repudiandae nihil asperiores",
                            PublishDate = new DateTime(2021, 8, 1, 6, 24, 52, 484, DateTimeKind.Local).AddTicks(6199),
                            Source = "https://elizabeth.com"
                        },
                        new
                        {
                            Id = new Guid("ed6b0e5d-487a-40df-bbb9-b252d30bd158"),
                            Name = "Voluptatem repellendus dolores",
                            PublishDate = new DateTime(2021, 10, 8, 9, 53, 40, 682, DateTimeKind.Local).AddTicks(6647),
                            Source = "https://marlen.net"
                        },
                        new
                        {
                            Id = new Guid("80ef931a-00b1-4fa1-b39d-bc0fc890b724"),
                            Name = "Et sunt esse",
                            PublishDate = new DateTime(2021, 4, 16, 8, 24, 21, 202, DateTimeKind.Local).AddTicks(7131),
                            Source = "https://geovanni.info"
                        },
                        new
                        {
                            Id = new Guid("009c0114-a0c3-4c2b-80e3-6e3d05ae14db"),
                            Name = "Aut sapiente quisquam",
                            PublishDate = new DateTime(2019, 10, 16, 1, 24, 36, 100, DateTimeKind.Local).AddTicks(5729),
                            Source = "https://destany.name"
                        },
                        new
                        {
                            Id = new Guid("d5a48db4-03d6-4c49-a6bb-cac362a550cf"),
                            Name = "Distinctio esse non",
                            PublishDate = new DateTime(2022, 1, 3, 12, 17, 47, 410, DateTimeKind.Local).AddTicks(4045),
                            Source = "https://mariane.com"
                        },
                        new
                        {
                            Id = new Guid("44f7a57d-63b2-4dfe-a463-f0338eec2205"),
                            Name = "Non voluptas qui",
                            PublishDate = new DateTime(2019, 11, 8, 17, 32, 15, 871, DateTimeKind.Local).AddTicks(7345),
                            Source = "http://asha.info"
                        },
                        new
                        {
                            Id = new Guid("7feb8741-056d-44c4-866a-fc6b8c10cbcc"),
                            Name = "Voluptatem qui tempore",
                            PublishDate = new DateTime(2019, 10, 12, 15, 40, 0, 129, DateTimeKind.Local).AddTicks(6911),
                            Source = "http://kaycee.biz"
                        },
                        new
                        {
                            Id = new Guid("7cd79461-8db0-4522-840a-a83c88ad389a"),
                            Name = "Impedit odit placeat",
                            PublishDate = new DateTime(2021, 10, 30, 5, 44, 43, 331, DateTimeKind.Local).AddTicks(8655),
                            Source = "http://moshe.name"
                        },
                        new
                        {
                            Id = new Guid("9e8c3e3e-3909-4178-a7b8-64c04041cef9"),
                            Name = "Aspernatur corporis quaerat",
                            PublishDate = new DateTime(2021, 10, 8, 13, 21, 20, 313, DateTimeKind.Local).AddTicks(7268),
                            Source = "http://merl.info"
                        },
                        new
                        {
                            Id = new Guid("f612c1e6-64b3-451b-ac0b-051589857666"),
                            Name = "Molestiae eum voluptatem",
                            PublishDate = new DateTime(2022, 9, 1, 14, 22, 58, 279, DateTimeKind.Local).AddTicks(97),
                            Source = "https://adele.com"
                        },
                        new
                        {
                            Id = new Guid("212eb0c2-52e6-4054-8235-cb21819a7865"),
                            Name = "Tempora magni fuga",
                            PublishDate = new DateTime(2022, 7, 7, 3, 23, 40, 541, DateTimeKind.Local).AddTicks(9077),
                            Source = "http://porter.com"
                        },
                        new
                        {
                            Id = new Guid("0e713713-bf70-425b-acda-3fc63063af1a"),
                            Name = "Aliquid a cumque",
                            PublishDate = new DateTime(2020, 6, 12, 11, 26, 39, 801, DateTimeKind.Local).AddTicks(7036),
                            Source = "http://lauretta.org"
                        },
                        new
                        {
                            Id = new Guid("26ee426b-bc90-452d-954e-cbbe496f1923"),
                            Name = "Quia eos consequatur",
                            PublishDate = new DateTime(2021, 2, 17, 9, 1, 32, 544, DateTimeKind.Local).AddTicks(9780),
                            Source = "http://deonte.name"
                        },
                        new
                        {
                            Id = new Guid("7327459c-6a1e-441d-8c02-3581dc88f530"),
                            Name = "Aut sit consequatur",
                            PublishDate = new DateTime(2021, 10, 6, 22, 13, 54, 436, DateTimeKind.Local).AddTicks(6573),
                            Source = "https://ricardo.org"
                        },
                        new
                        {
                            Id = new Guid("516cfead-02e6-42d4-91ad-80ccf3af9058"),
                            Name = "Sit debitis voluptates",
                            PublishDate = new DateTime(2020, 9, 2, 17, 21, 34, 284, DateTimeKind.Local).AddTicks(1946),
                            Source = "http://gonzalo.net"
                        },
                        new
                        {
                            Id = new Guid("d696ae3c-8855-4033-8505-cdebad1cd551"),
                            Name = "Quia vitae velit",
                            PublishDate = new DateTime(2021, 9, 15, 5, 32, 2, 756, DateTimeKind.Local).AddTicks(2603),
                            Source = "https://bernardo.net"
                        },
                        new
                        {
                            Id = new Guid("7d259cae-ee76-475e-ba23-a20178f2567c"),
                            Name = "Similique sed ad",
                            PublishDate = new DateTime(2021, 4, 5, 8, 24, 0, 868, DateTimeKind.Local).AddTicks(6646),
                            Source = "http://edward.biz"
                        },
                        new
                        {
                            Id = new Guid("1c746e7f-5c94-4901-9f61-32e5f74ea058"),
                            Name = "A commodi quia",
                            PublishDate = new DateTime(2020, 6, 4, 0, 24, 37, 475, DateTimeKind.Local).AddTicks(9323),
                            Source = "http://scot.info"
                        },
                        new
                        {
                            Id = new Guid("c9dc7b2e-cee5-44c1-8d96-298415ff5b12"),
                            Name = "Qui aperiam voluptas",
                            PublishDate = new DateTime(2021, 8, 18, 6, 7, 50, 83, DateTimeKind.Local).AddTicks(846),
                            Source = "https://kylee.info"
                        },
                        new
                        {
                            Id = new Guid("a8eaa7fc-7279-4784-a740-7b003ee3829a"),
                            Name = "Voluptatibus commodi officia",
                            PublishDate = new DateTime(2020, 5, 15, 22, 28, 12, 569, DateTimeKind.Local).AddTicks(9864),
                            Source = "https://imelda.biz"
                        },
                        new
                        {
                            Id = new Guid("30567ee6-5cb7-405b-bfd3-672175885860"),
                            Name = "Nihil et ea",
                            PublishDate = new DateTime(2021, 7, 16, 12, 30, 5, 293, DateTimeKind.Local).AddTicks(7042),
                            Source = "https://marge.biz"
                        },
                        new
                        {
                            Id = new Guid("27540a9a-ec2d-4647-95dd-a26a900774d1"),
                            Name = "Quas id quos",
                            PublishDate = new DateTime(2022, 1, 29, 22, 27, 10, 852, DateTimeKind.Local).AddTicks(3150),
                            Source = "https://maya.org"
                        },
                        new
                        {
                            Id = new Guid("9d385160-b210-4984-9c29-6216cffbd068"),
                            Name = "Sapiente veritatis ad",
                            PublishDate = new DateTime(2020, 1, 2, 15, 55, 27, 153, DateTimeKind.Local).AddTicks(5967),
                            Source = "https://adeline.net"
                        },
                        new
                        {
                            Id = new Guid("78f6d540-8e3f-4252-b2d3-7df31f9cdc88"),
                            Name = "Voluptatum sunt nemo",
                            PublishDate = new DateTime(2019, 9, 30, 21, 0, 1, 603, DateTimeKind.Local).AddTicks(980),
                            Source = "http://elmira.com"
                        },
                        new
                        {
                            Id = new Guid("e5b173f1-434a-4bae-af02-1c42cc2de0c2"),
                            Name = "Dolores quia odio",
                            PublishDate = new DateTime(2020, 6, 24, 11, 54, 58, 73, DateTimeKind.Local).AddTicks(1077),
                            Source = "https://edmond.biz"
                        },
                        new
                        {
                            Id = new Guid("d5d3bb16-8940-4697-8e4e-a624db09ac67"),
                            Name = "Sint pariatur omnis",
                            PublishDate = new DateTime(2021, 12, 22, 15, 17, 55, 95, DateTimeKind.Local).AddTicks(222),
                            Source = "http://eveline.biz"
                        },
                        new
                        {
                            Id = new Guid("734b9d1b-5f1c-4e7d-bd86-6ce4d745b9ce"),
                            Name = "Dolores delectus aliquid",
                            PublishDate = new DateTime(2022, 5, 29, 11, 58, 45, 588, DateTimeKind.Local).AddTicks(8074),
                            Source = "http://buck.net"
                        },
                        new
                        {
                            Id = new Guid("5039a7ac-c910-4901-8dbb-ac57337f1a89"),
                            Name = "Qui necessitatibus facilis",
                            PublishDate = new DateTime(2020, 12, 26, 23, 45, 17, 242, DateTimeKind.Local).AddTicks(5115),
                            Source = "https://oswaldo.net"
                        },
                        new
                        {
                            Id = new Guid("e3771edc-03b0-489a-a2d7-d61a63a64862"),
                            Name = "Officia voluptas eos",
                            PublishDate = new DateTime(2020, 2, 7, 19, 27, 24, 159, DateTimeKind.Local).AddTicks(5996),
                            Source = "https://halie.name"
                        },
                        new
                        {
                            Id = new Guid("4bc79f2f-dbc8-4be5-aab5-c7a4f1c94cfc"),
                            Name = "Ipsa velit incidunt",
                            PublishDate = new DateTime(2021, 10, 4, 14, 7, 14, 835, DateTimeKind.Local).AddTicks(713),
                            Source = "https://maybell.net"
                        },
                        new
                        {
                            Id = new Guid("52d73c52-6419-404d-b3c3-0c29f64b6edd"),
                            Name = "Aut quasi quia",
                            PublishDate = new DateTime(2022, 7, 16, 19, 56, 29, 209, DateTimeKind.Local).AddTicks(9488),
                            Source = "https://jonas.biz"
                        },
                        new
                        {
                            Id = new Guid("0244c8b7-fdd2-4d5a-b79d-f20448118425"),
                            Name = "Dolores molestiae dolorem",
                            PublishDate = new DateTime(2021, 4, 5, 2, 0, 35, 630, DateTimeKind.Local).AddTicks(5775),
                            Source = "http://delmer.org"
                        },
                        new
                        {
                            Id = new Guid("bd788e23-c9cb-457e-afe5-e23a126adf19"),
                            Name = "Corrupti cumque itaque",
                            PublishDate = new DateTime(2021, 7, 28, 18, 13, 34, 142, DateTimeKind.Local).AddTicks(2311),
                            Source = "https://kaia.info"
                        },
                        new
                        {
                            Id = new Guid("528089ce-d06f-43e6-bffa-409057e2a558"),
                            Name = "Et eum est",
                            PublishDate = new DateTime(2020, 3, 26, 8, 51, 25, 253, DateTimeKind.Local).AddTicks(8703),
                            Source = "https://ethyl.com"
                        },
                        new
                        {
                            Id = new Guid("ec2d80af-fa60-4110-9321-bd97947f1a2e"),
                            Name = "Consequuntur ut sed",
                            PublishDate = new DateTime(2022, 6, 15, 4, 2, 35, 154, DateTimeKind.Local).AddTicks(1462),
                            Source = "https://willis.net"
                        },
                        new
                        {
                            Id = new Guid("a9701275-48a5-4cee-8465-e75c8b392cd1"),
                            Name = "Dolores delectus id",
                            PublishDate = new DateTime(2020, 7, 15, 6, 45, 38, 85, DateTimeKind.Local).AddTicks(1409),
                            Source = "https://desmond.com"
                        },
                        new
                        {
                            Id = new Guid("a803b4da-8c66-4b4f-94c5-608fc81ee0e4"),
                            Name = "Harum mollitia suscipit",
                            PublishDate = new DateTime(2021, 7, 3, 9, 1, 44, 442, DateTimeKind.Local).AddTicks(340),
                            Source = "http://nathanael.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
